// Generated by CoffeeScript 2.7.0
(function() {
  var Hs, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  // !!!! Hotpoor root object
  root.Hs || (root.Hs = {});

  Hs = root.Hs;

  Hs.base_width = 750;

  Hs.base_height = 1334;

  Hs.window_resize = function() {
    var window_height;
    window_height = document.querySelector("body").offsetHeight;
    Hs.current_width = window_height / Hs.base_height * Hs.base_width;
    Hs.current_height = window_height;
    document.querySelector(".page").style.width = `${Hs.current_width}px`;
    return document.querySelector(".page").style.height = `${Hs.current_height}px`;
  };

  (function() {
    Hs.media_play = function() {
      return document.querySelector("#media").play();
    };
    Hs.media_pasure = function() {
      return document.querySelector("#media").pause();
    };
    window.addEventListener("load", function(evt) {
      return Hs.window_resize();
    });
    return window.addEventListener("resize", function(evt) {
      return Hs.window_resize();
    });
  })();

}).call(this);
